server:
  port: 8080
  servlet:
      context-path: /CETBoot/api

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/cet_boot?rewriteBatchedStatements=true
    hikari:
      minimum-idle: 3
      auto-commit: true
      maximum-pool-size: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  profiles:
    active: '@env@'
  cache:
    redis:
      key-prefix: cetboot
      use-key-prefix: true
  servlet:
    multipart:
      max-file-size: 10MB

logging:
  file:
    path: logs
  level:
    com.code.cetboot: debug


sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: Authorization
  # token前缀
  token-prefix: Bearer
  # 是否尝试从header里读取token
  is-read-header: true
  # 是否从 Cookie 读取 Token
  is-read-cookie: false
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true

file:
  filePath: E:\cetboot\file\
  audioPath: E:\cetboot\audio\

# 文件访问地址
webPath:
  file: /file/download/
  audio: /audio/